remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
title: Edwin's Documenation
description: Edwin is a .Net developer all his findings are here
show_downloads: flase
google_analytics:
theme: jekyll-theme-time-machine