remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
markdown: kramdown
title: Edwin's Documentatie
description: Edwin is een .Net developer al zijn bevindingen staat hier
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine